"use client";

import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { Flashcard } from "@/components/Flashcard";
import { Brain, Sparkles, ArrowLeft } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/Button";
import { MOCK_MENTORS } from "@/lib/mockMentors";

// Dynamic RAG response based on mentor
const generateMockAIFlashcards = (mentorId: number) => {
  const mentor = MOCK_MENTORS.find(m => m.id === mentorId) || MOCK_MENTORS[0];
  const topics = mentor.expertise.split(',').map(t => t.trim());
  
  if (mentorId === 1) {
    return [
      { front: "Wave-Particle Duality", back: "The concept in quantum mechanics that every particle or quantum entity may be described as either a particle or a wave." },
      { front: "De Broglie Wavelength", back: "λ = h/p, where h is Planck's constant and p is momentum. Shows the relationship between a particle's momentum and its wavelength." },
      { front: "Photoelectric Effect", back: "The emission of electrons when electromagnetic radiation, such as light, hits a material. Proves the particle nature of light (photons)." }
    ];
  }
  
  return topics.map(topic => ({
    front: `Key Concept: ${topic}`,
    back: `This flashcard was automatically extracted from your mentorship sessions with ${mentor.name}. It covers the core fundamentals of ${topic} based on their background as a ${mentor.profession}.`
  }));
};

export default function FlashcardsHub() {
  const [selectedMentorId, setSelectedMentorId] = useState<number>(MOCK_MENTORS[0].id);
  const [flashcards, setFlashcards] = useState<{front: string, back: string}[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    // Simulate RAG extraction from past transcripts
    const timer = setTimeout(() => {
      setFlashcards(generateMockAIFlashcards(selectedMentorId));
      setLoading(false);
    }, 1200);
    return () => clearTimeout(timer);
  }, [selectedMentorId]);

  const mentor = MOCK_MENTORS.find(m => m.id === selectedMentorId) || MOCK_MENTORS[0];

  return (
    <div className="max-w-5xl mx-auto px-4 py-8 min-h-screen flex flex-col">
      <Link href="/dashboard/student">
        <Button variant="ghost" className="mb-6 gap-2 text-muted-foreground hover:text-foreground">
          <ArrowLeft size={16} /> Back to Dashboard
        </Button>
      </Link>

      <div className="mb-10 text-center">
        <motion.div
          initial={{ scale: 0 }}
          animate={{ scale: 1 }}
          transition={{ type: "spring", bounce: 0.5 }}
          className="w-16 h-16 mx-auto bg-primary/20 rounded-full flex items-center justify-center mb-4"
        >
          <Sparkles className="w-8 h-8 text-primary" />
        </motion.div>
        <h1 className="text-4xl font-bold mb-4">AI Knowledge RAG</h1>
        <p className="text-muted-foreground text-lg max-w-2xl mx-auto mb-6">
          These flashcards were automatically generated by our LangChain agents analyzing your past session transcripts.
        </p>
        
        <div className="max-w-md mx-auto">
          <label className="text-sm text-muted-foreground font-medium mb-2 block text-left">Generate flashcards from sessions with:</label>
          <select 
            className="w-full h-12 px-4 py-2 rounded-md border border-border bg-background/50 text-foreground focus:outline-none focus:ring-2 focus:ring-primary glass"
            value={selectedMentorId}
            onChange={(e) => setSelectedMentorId(Number(e.target.value))}
          >
            {MOCK_MENTORS.map(m => (
              <option key={m.id} value={m.id}>{m.name} ({m.profession})</option>
            ))}
          </select>
        </div>
      </div>

      {loading ? (
        <div className="flex-1 flex flex-col items-center justify-center py-20 opacity-50">
          <Brain className="w-12 h-12 text-primary animate-pulse mb-4" />
          <p className="text-lg">Extracting key concepts from {mentor.name}'s transcripts...</p>
        </div>
      ) : (
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8"
        >
          {flashcards.map((card, index) => (
            <motion.div 
              key={index}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.15 }}
            >
              <Flashcard front={card.front} back={card.back} />
            </motion.div>
          ))}
        </motion.div>
      )}
    </div>
  );
}
