export interface Mentor {
  id: number;
  name: string;
  expertise: string;
  profession: string;
}

export const MOCK_MENTORS: Mentor[] = [
  { id: 1, name: "Dr. Rajesh Sharma", profession: "Retired Physics Professor", expertise: "Physics for JEE Mains, Quantum Mechanics, Thermodynamics" },
  { id: 2, name: "Dr. Sneha Patel", profession: "Former ISRO Scientist", expertise: "Aerospace Engineering, Satellite Navigation, Astrophysics" },
  { id: 3, name: "Mr. Vikram Singh", profession: "Ex-Chief Engineer at L&T", expertise: "Civil Engineering, Structural Mechanics, Construction Tech" },
  { id: 4, name: "Dr. Anjali Desai", profession: "Retired Head of Cardiology", expertise: "Human Biology, Anatomy, Medical Entrance Prep (NEET)" },
  { id: 5, name: "Prof. Amit Kumar", profession: "Former IIT Mathematics Professor", expertise: "Advanced Calculus, Linear Algebra, Number Theory" },
  { id: 6, name: "Mrs. Sunita Rao", profession: "Retired CFO", expertise: "Financial Literacy, Accounting, Business Mathematics" },
  { id: 7, name: "Dr. Rohan Mehta", profession: "Former Senior Chemist at Cipla", expertise: "Organic Chemistry, Pharmaceuticals, Chemical Reactions" },
  { id: 8, name: "Mr. Prakash Nair", profession: "Ex-Software Architect at Infosys", expertise: "Computer Science, Java, System Design, Data Structures" },
  { id: 9, name: "Dr. Kavita Joshi", profession: "Retired Botanist", expertise: "Plant Biology, Environmental Science, Botany" },
  { id: 10, name: "Mr. Anil Kapoor", profession: "Former High Court Judge", expertise: "Civics, Indian Constitution, Law, Political Science" },
  { id: 11, name: "Prof. Meera Reddy", profession: "Retired Historian", expertise: "Indian History, World War II, Ancient Civilizations" },
  { id: 12, name: "Dr. Suresh Iyer", profession: "Former Lead Economist", expertise: "Macroeconomics, Microeconomics, Global Trade" },
  { id: 13, name: "Mrs. Lakshmi Menon", profession: "Retired English Literature Professor", expertise: "English Grammar, Shakespeare, Creative Writing" },
  { id: 14, name: "Mr. Rajiv Bhatia", profession: "Ex-Naval Commander", expertise: "Marine Navigation, Leadership, Geography" },
  { id: 15, name: "Dr. Neha Gupta", profession: "Former Research Psychologist", expertise: "Psychology, Mental Health, Cognitive Science" },
  { id: 16, name: "Prof. Anand Tiwari", profession: "Retired Sociology Head", expertise: "Sociology, Cultural Studies, Social Issues" },
  { id: 17, name: "Mr. Deepak Verma", profession: "Ex-Automobile Engineer at Tata", expertise: "Mechanical Engineering, Thermodynamics, Auto Mechanics" },
  { id: 18, name: "Dr. Priya Sharma", profession: "Retired Geneticist", expertise: "Genetics, DNA Sequencing, Biotechnology" },
  { id: 19, name: "Mr. Sanjay Dutt", profession: "Former Supply Chain Director", expertise: "Logistics, Supply Chain Management, Operations" },
  { id: 20, name: "Mrs. Anita Desai", profession: "Retired Geologist", expertise: "Earth Sciences, Geology, Plate Tectonics" },
  { id: 21, name: "Dr. Ramesh Babu", profession: "Former Neurologist", expertise: "Neuroscience, Brain Anatomy, Biology" },
  { id: 22, name: "Prof. Kiran Kumar", profession: "Retired Linguistics Professor", expertise: "Linguistics, Etymology, Language Evolution" },
  { id: 23, name: "Mr. Arjun Singh", profession: "Ex-Wildlife Photographer", expertise: "Photography, Wildlife Conservation, Zoology" },
  { id: 24, name: "Dr. Shalini Jain", profession: "Former Pharmacologist", expertise: "Pharmacology, Medicine, Chemistry" },
  { id: 25, name: "Mr. Vijay Mallya", profession: "Retired Aerospace Engineer", expertise: "Aerodynamics, Fluid Mechanics, Physics" },
  { id: 26, name: "Mrs. Pooja Chawla", profession: "Former Art Director", expertise: "Fine Arts, Art History, Design Principles" },
  { id: 27, name: "Dr. Arvind Swamy", profession: "Retired Microbiologist", expertise: "Microbiology, Virology, Cellular Biology" },
  { id: 28, name: "Prof. Ritu Kapoor", profession: "Former Economics Professor", expertise: "Econometrics, Game Theory, Statistics" },
  { id: 29, name: "Mr. Hari Prasad", profession: "Ex-Agricultural Scientist", expertise: "Agriculture, Soil Science, Agronomy" },
  { id: 30, name: "Dr. Smita Patil", profession: "Retired Anthropologist", expertise: "Anthropology, Human Evolution, Archaeology" },
  { id: 31, name: "Mr. Kamal Haasan", profession: "Former Diplomat", expertise: "International Relations, Foreign Policy, Civics" },
  { id: 32, name: "Mrs. Rekha Bhardwaj", profession: "Retired Musicologist", expertise: "Indian Classical Music, Acoustics, Sound Physics" },
  { id: 33, name: "Dr. Mohanlal", profession: "Former Marine Biologist", expertise: "Marine Biology, Oceanography, Ecology" },
  { id: 34, name: "Prof. Vidya Balan", profession: "Retired Philosophy Professor", expertise: "Ethics, Logic, Western Philosophy" },
  { id: 35, name: "Mr. Nagesh Kukunoor", profession: "Ex-Chemical Engineer", expertise: "Chemical Engineering, Polymer Science, Material Science" },
  { id: 36, name: "Dr. Shabana Azmi", profession: "Former Public Health Official", expertise: "Epidemiology, Public Health, Biology" },
  { id: 37, name: "Mr. Anupam Kher", profession: "Retired Theatre Director", expertise: "Performing Arts, Literature, Public Speaking" },
  { id: 38, name: "Mrs. Nandita Das", profession: "Former Urban Planner", expertise: "Urban Planning, Geography, Demographics" },
  { id: 39, name: "Dr. Naseeruddin Shah", profession: "Retired Astrophysicist", expertise: "Astrophysics, Cosmology, Astronomy" },
  { id: 40, name: "Prof. Om Puri", profession: "Former Political Science Head", expertise: "Political Theory, Governance, Public Administration" },
  { id: 41, name: "Mr. Irrfan Khan", profession: "Ex-Data Scientist", expertise: "Data Science, Machine Learning, Artificial Intelligence" },
  { id: 42, name: "Dr. Tabu", profession: "Retired Endrocrinologist", expertise: "Endocrinology, Human Physiology, Biology" },
  { id: 43, name: "Mrs. Konkona Sen", profession: "Former Journalist", expertise: "Media Studies, Journalism, Mass Communication" },
  { id: 44, name: "Mr. Manoj Bajpayee", profession: "Ex-Civil Servant", expertise: "Public Policy, Indian Administration, Civics" },
  { id: 45, name: "Dr. Radhika Apte", profession: "Retired Quantum Physicist", expertise: "Quantum Computing, Theoretical Physics, Mechanics" },
  { id: 46, name: "Prof. Pankaj Tripathi", profession: "Former Literature Professor", expertise: "Hindi Literature, Poetry, Dramatics" },
  { id: 47, name: "Mr. Nawazuddin Siddiqui", profession: "Ex-Forensic Scientist", expertise: "Forensic Science, Criminology, Chemistry" },
  { id: 48, name: "Mrs. Richa Chadha", profession: "Retired Environmentalist", expertise: "Climate Change, Environmental Studies, Ecology" },
  { id: 49, name: "Dr. Kay Kay Menon", profession: "Former Meteorologist", expertise: "Meteorology, Weather Patterns, Physics" },
  { id: 50, name: "Mr. Boman Irani", profession: "Ex-Commercial Pilot", expertise: "Aviation, Navigation, Aerodynamics" },
];
